src/Entity/Association.php
<?php

namespace App\Entity;

use App\Enum\AssociationCategory;
use App\Repository\AssociationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use RRule\RRule;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: AssociationRepository::class)]
class Association
{
    use TimestampableEntity;
    use BlameableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(['autocomplete'])]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Groups(['autocomplete'])]
    private string $name;

    #[ORM\Column(type: Types::STRING, length: 255, unique: true)]
    #[Groups(['autocomplete'])]
    #[Gedmo\Slug(fields: ['name'])]
    private string $slug;

    #[ORM\Column(type: Types::JSON, nullable: true, enumType: AssociationCategory::class)]
    #[Groups(['autocomplete'])]
    private ?array $categories = [];

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    #[Groups(['autocomplete'])]
    private ?string $logoFilename = null;

    /** @var Collection<int, Contact> */
    #[ORM\OneToMany(targetEntity: Contact::class, mappedBy: 'association', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $contacts;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $contactEmail = null;

    #[ORM\Column(type: Types::STRING, length: 32, nullable: true)]
    private ?string $contactPhone = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $contactAddress = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $networkWebsite = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $networkFacebook = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $networkInstagram = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $networkOther = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\OneToMany(targetEntity: AssociationRevision::class, mappedBy: 'association', cascade: ['persist', 'remove'])]
    #[ORM\OrderBy(['id' => 'ASC'])]
    private Collection $revisions;

    #[ORM\OneToMany(targetEntity: Event::class, mappedBy: 'association', cascade: ['persist', 'remove'])]
    private Collection $events;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'chairedAssociations')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $owner = null;

    /** @var Collection<int, Subscription> */
    #[ORM\OneToMany(targetEntity: Subscription::class, mappedBy: 'association')]
    private Collection $subscriptions;

    /** @var Collection<int, Membership> */
    #[ORM\OneToMany(targetEntity: Membership::class, mappedBy: 'association')]
    private Collection $memberships;

    #[ORM\Column(nullable: false, options: ['default' => true])]
    private bool $editablePageAnonymously = true;

    #[ORM\Column(nullable: false, options: ['default' => false])]
    private bool $editableEventsAnonymously = false;

    public function __construct()
    {
        $this->revisions = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
        $this->subscriptions = new ArrayCollection();
        $this->memberships = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function serialize(): array
    {
        return [
            'name' => $this->name,
            'slug' => $this->slug,
            'categories' => implode(',', $this->getCategoriesValues()),
            'logoFilename' => $this->logoFilename,
            'contacts' => implode(',', $this->getContactsValues()),
            'contactEmail' => $this->contactEmail,
            'contactPhone' => $this->contactPhone,
            'contactAddress' => $this->contactAddress,
            'networkWebsite' => $this->networkWebsite,
            'networkFacebook' => $this->networkFacebook,
            'networkInstagram' => $this->networkInstagram,
            'networkOther' => $this->networkOther,
            'content' => $this->content,
        ];
    }

    public function unserialize(array $data): self
    {
        $this->name = $data['name'];
        $this->slug = $data['slug'];
        $this->categories = array_map(
            fn (string $value) => AssociationCategory::from($value),
            explode(',', $data['categories']) ?? []
        );
        $this->logoFilename = $data['logoFilename'];
        $this->contacts = new ArrayCollection(array_map(function ($item) {
            [$function, $name] = explode('|', $item);
            $contact = new Contact();
            $contact->setFunction($function);
            $contact->setName($name);

            return $contact;
        }, explode(',', $data['contacts'])));
        $this->contactEmail = $data['contactEmail'];
        $this->contactPhone = $data['contactPhone'];
        $this->contactAddress = $data['contactAddress'];
        $this->networkWebsite = $data['networkWebsite'];
        $this->networkFacebook = $data['networkFacebook'];
        $this->networkInstagram = $data['networkInstagram'];
        $this->networkOther = $data['networkOther'];
        $this->content = $data['content'];

        return $this;
    }

    public function isWip(): bool
    {
        return $this->updatedBy = 'batch' && str_starts_with($this->updatedAt->format('Y-m-d H:i:s'), '2025-09-25 17:');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): Association
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategories(): ?array
    {
        return $this->categories;
    }

    public function getCategoriesValues(): ?array
    {
        $categories = [];
        /** @var AssociationCategory $category */
        foreach ($this->categories as $category) {
            $categories[] = $category->value;
        }

        return $categories;
    }

    public function setCategories(?array $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getLogoFilename(): ?string
    {
        return $this->logoFilename;
    }

    public function setLogoFilename(?string $logoFilename): self
    {
        $this->logoFilename = $logoFilename;

        return $this;
    }

    /** @return Collection<int, Contact> */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function getContactsValues(): ?array
    {
        $contacts = [];
        /** @var Contact $contact */
        foreach ($this->contacts as $contact) {
            $contacts[] = sprintf('%s|%s', $contact->getFunction(), $contact->getName());
        }

        return $contacts;
    }

    public function addContact(Contact $contact): static
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts->add($contact);
            $contact->setAssociation($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): static
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getAssociation() === $this) {
                $contact->setAssociation(null);
            }
        }

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contactEmail;
    }

    public function setContactEmail(?string $contactEmail): self
    {
        $this->contactEmail = $contactEmail;

        return $this;
    }

    public function getContactPhone(): ?string
    {
        return $this->contactPhone;
    }

    public function setContactPhone(?string $contactPhone): self
    {
        $this->contactPhone = $contactPhone;

        return $this;
    }

    public function getContactAddress(): ?string
    {
        return $this->contactAddress;
    }

    public function setContactAddress(?string $contactAddress): self
    {
        $this->contactAddress = $contactAddress;

        return $this;
    }

    public function hasAnyContactDetail(): bool
    {
        return $this->contacts->count() > 0 || !empty($this->contactEmail) || !empty($this->contactPhone) || !empty($this->contactAddress);
    }

    public function getNetworkWebsite(): ?string
    {
        return $this->networkWebsite;
    }

    public function setNetworkWebsite(?string $networkWebsite): self
    {
        $this->networkWebsite = $networkWebsite;

        return $this;
    }

    public function getNetworkFacebook(): ?string
    {
        return $this->networkFacebook;
    }

    public function setNetworkFacebook(?string $networkFacebook): self
    {
        $this->networkFacebook = $networkFacebook;

        return $this;
    }

    public function getNetworkInstagram(): ?string
    {
        return $this->networkInstagram;
    }

    public function setNetworkInstagram(?string $networkInstagram): self
    {
        $this->networkInstagram = $networkInstagram;

        return $this;
    }

src/Form/AssociationType.php
<?php

namespace App\Form;

use App\Entity\Association;
use App\Enum\AssociationCategory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AssociationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'association.form.name',
            ])
        ;

        if (!$options['pre_new']) {
            $builder
                ->add('categories', ChoiceType::class, [
                    'choices' => AssociationCategory::cases(),
                    'choice_value' => fn (?AssociationCategory $category) => $category?->value,
                    'choice_label' => fn (AssociationCategory $category) => 'association.category.'.$category->value,
                    'multiple' => true,
                    'required' => false,
                    'label' => 'association.form.categories',
                ])
                ->add('logo', FileType::class, [
                    'label' => 'association.form.logo',
                    'mapped' => false,
                    'required' => false,
                ])
                ->add('contacts', CollectionType::class, [
                    'required' => false,
                    'entry_type' => ContactType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                    'by_reference' => false,
                    'prototype' => true,
                    'label' => false,
                    'entry_options' => [
                        'label' => false,
                    ],
                ])
                ->add('contactEmail', EmailType::class, [
                    'label' => 'association.form.contact.email',
                    'required' => false,
                ])
                ->add('contactPhone', TextType::class, [
                    'label' => 'association.form.contact.phone',
                    'required' => false,
                ])
                ->add('contactAddress', TextType::class, [
                    'label' => 'association.form.contact.address',
                    'required' => false,
                ])
                ->add('networkWebsite', TextType::class, [
                    'label' => 'association.form.network.website',
                    'required' => false,
                ])
                ->add('networkFacebook', TextType::class, [
                    'label' => 'association.form.network.facebook',
                    'required' => false,
                ])
                ->add('networkInstagram', TextType::class, [
                    'label' => 'association.form.network.instagram',
                    'required' => false,
                ])
                ->add('networkOther', TextType::class, [
                    'label' => 'association.form.network.other',
                    'required' => false,
                ])
                ->add('content', TextareaType::class, [
                    'label' => false,
                ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Association::class,
            'pre_new' => false,
        ]);
    }
}

templates/association/_list.html.twig
{% if associations is not empty %}
    {% set grouped = {} %}

    {% for association in associations %}
        {% set firstLetter = association.name|first|upper %}
        {% if grouped[firstLetter] is not defined %}
            {% set grouped = grouped|merge({ (firstLetter): [association] }) %}
        {% else %}
            {% set grouped = grouped|merge({ (firstLetter): grouped[firstLetter]|merge([association]) }) %}
        {% endif %}
    {% endfor %}

    <div class="masonry">
        {% for letter in grouped|keys|sort %}
            <div class="col">
                <h4 class="mt-3">{{ letter }}</h4>
                <div class="list-group mb-3">
                    {% for assoc in grouped[letter]|sort((a, b) => a.name <=> b.name) %}
                        <a href="{{ path('association_show', {slug: assoc.slug}) }}" class="list-group-item list-group-item-action {% if assoc.wip %}wip{% endif%} d-flex justify-content-between" data-categories="{{ assoc.categories|json_encode }}">
                            <div>
                                {% if assoc.wip %}
                                    <span title="{{ 'association.wip'|trans }}">
                                        {% include 'common/construction-cone.svg.twig' %}
                                    </span>
                                {% endif %}
                                <span>
                                    {{ assoc.name|mark(searchTerm|default) }}{% if app.user|default and app.user.isSubscribedTo(assoc) %}&nbsp;<i class="fa fa-star text-warning" title="{{ 'association.subscription.info'|trans }}"></i>{% endif %}
                                </span>
                            </div>
                            <span>
                                {% if assoc.categories|default %}
                                    {% for category in assoc.categories %}
                                        <i class="{{ category.icon }} text-{{ category.badge }}" title="{{ ('association.category.' ~ category.value)|trans }}"></i>&nbsp;
                                    {% endfor %}
                                {% endif %}
                            </span>
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div class="alert alert-info mt-3">{{ customEmptyMessage is defined ? customEmptyMessage : 'home.associations.list.none'|trans }}</div>
{% endif %}

templates/association/_revisions-preview.html.twig
<div class="modal" id="revisionPreviewModal" tabindex="-1">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ 'revision.modal.title'|trans }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"></div>
            {% if is_granted('edit', association) %}
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        {{ 'revision.modal.actions.cancel'|trans }}
                    </button>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/association/contact_fields.html.twig
{% block contact_entry_widget %}
    <div class="contact-entry row pe-4 position-relative">
        <div class="col-md-6">
            {{ form_row(form.name, {'label_attr': {'class': 'my-2'},'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.function, {'label_attr': {'class': 'my-2'},'attr': {'class': 'form-control'}}) }}
        </div>

        <span class="remove-contact py-2" title="{{ 'contact.form.remove'|trans }}"><i class="fa fa-times"></i></span>
    </div>
{% endblock %}

templates/association/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'association.edit.title'|trans({'%association%': association.name}) }}{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between">
        <h1>{{ 'association.edit.title'|trans({'%association%': association.name}) }}</h1>
    </div>

    {{ form_start(formAssociation) }}
        {% include 'association/form.html.twig' with {formAssociation: formAssociation} %}

        <div class="mt-3 d-flex justify-content-between">
            <a href="{{ path('association_show', { slug: association.slug }) }}" class="btn btn-secondary mt-3">
                <i class="fa fa-arrow-left"></i>&nbsp;{{ 'association.edit.cancel'|trans }}
            </a>

            <button type="submit" class="btn btn-success text-white mt-3">
                <i class="fa fa-save"></i>&nbsp;{{ 'association.edit.save'|trans }}
            </button>
        </div>
    {{ form_end(formAssociation) }}

    <div class="d-flex flex-column align-items-center ">
        <p class="mt-3 mb-1 text-center fst-italic">
            {{ 'association.show.creation'|trans({
                createdAt: format_date(association.createdAt)|lower,
                updatedAt: format_date(association.updatedAt)|lower,
            }) }}
        </p>

        {% if association.revisions|default|length > 0 %}
            <div class="dropup m-0 p-0">
                <button class="btn btn-link dropdown-toggle p-0" type="button" id="dropdownRevisions" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ 'revision.title'|trans }}
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownRevisions">
                    {% for revision in association.revisions|reverse|slice(0, 5) %}
                        <li>
                            <a class="dropdown-item revision-preview" href="javascript:void(0);" data-href="{{ path('association_rollback_preview', {slug: association.slug, revisionId: revision.id}) }}">
                                {% if revision.createdBy|default %}
                                    {{ 'revision.created_at_by'|trans({
                                        'createdAt': revision.createdAt|date('Y-m-d \\à H:i:s'),
                                        'createdBy': revision.createdBy
                                    }) }}
                                {% else %}
                                    {{ 'revision.created_at'|trans({
                                        'createdAt': revision.createdAt|date('Y-m-d \\à H:i:s')
                                    }) }}
                                {% endif %}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            {% include 'association/_revisions-preview.html.twig' %}
        {% endif %}
    </div>
{% endblock %}

templates/association/form.html.twig
<div>
    {{ form_row(formAssociation.name, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control', 'autocomplete': 'off'}}) }}
</div>

{% if formAssociation.categories is defined %}
    <div>
        {{ form_row(formAssociation.categories, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-select js-tomselect'}}) }}
    </div>
{% endif %}

{% if formAssociation.logo is defined %}
    <div>
        {% if association.logoFilename|default %}
            <div class="row">
                <div class="col-md-8">
                    {{ form_row(formAssociation.logo, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-4 d-flex align-items-end p-3">
                    <img src="/uploads/{{ association.logoFilename }}" alt="{{ association.name }}" class="img-fluid img-thumbnail">
                </div>
            </div>
        {% else %}
            {{ form_row(formAssociation.logo, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
        {% endif %}
    </div>
    <hr class="my-5">
{% endif %}

{% if formAssociation.contacts is defined %}
    <div>
        {% form_theme formAssociation.contacts 'association/contact_fields.html.twig' %}
        <fieldset class="row">
            <legend>{{ 'association.form.contact.title'|trans }} <small><em>({{ 'association.form.optional'|trans }}</em></small>)</legend>
            <div class="col-md-12">
                <div id="contacts-collection" data-prototype="{{ form_widget(formAssociation.contacts.vars.prototype)|e('html_attr') }}">
                    {{ form_row(formAssociation.contacts) }}
                </div>

                <button type="button" class="btn btn-link text-primary ps-0" id="add-contact">Ajouter un contact</button>
            </div>
            <div class="col-md-12">
                {{ form_row(formAssociation.contactAddress, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col-md-6">
                {{ form_row(formAssociation.contactEmail, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col-md-6">
                {{ form_row(formAssociation.contactPhone, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
        </fieldset>
    </div>
    <hr class="my-5">
{% endif %}

{% if formAssociation.networkWebsite is defined %}
    <div>
        <fieldset class="row">
            <legend>{{ 'association.form.network.title'|trans }} <small><em>({{ 'association.form.optional'|trans }}</em></small>)</legend>
            <div class="col-md-6">
                {{ form_row(formAssociation.networkWebsite, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col-md-6">
                {{ form_row(formAssociation.networkFacebook, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col-md-6">
                {{ form_row(formAssociation.networkInstagram, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="col-md-6">
                {{ form_row(formAssociation.networkOther, {'label_attr': {'class': 'my-2'}, 'attr': {'class': 'form-control'}}) }}
            </div>
        </fieldset>
    </div>
    <hr class="my-5">
{% endif %}

{% if formAssociation.content is defined %}
    <div>
        <fieldset>
            <legend>{{ 'association.form.content'|trans }}</legend>
            <p>{{ 'association.form.content_help'|trans }}</p>
            {{ form_row(formAssociation.content, {'attr': {'class': 'form-control wysiwyg page-template'}}) }}
        </fieldset>
    </div>
{% endif %}

templates/association/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'association.add.title'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'association.add.title'|trans }}</h1>

    {{ form_start(form) }}
        {% include 'association/form.html.twig' with {formAssociation: form} %}

        <div class="mt-3 d-flex justify-content-end">
            <button type="submit" class="btn btn-success text-white mt-3">
                <i class="fa fa-save"></i>&nbsp;{{ 'association.edit.save'|trans }}
            </button>
        </div>
    {{ form_end(form) }}
{% endblock %}

templates/association/pre-new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'association.add.title'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'association.add.title'|trans }}</h1>

    {{ form_start(form) }}
        {% include 'association/form.html.twig' with {formAssociation: form} %}
    {{ form_end(form) }}

    <div id="results" class="d-none">
        <h2>S'agit-il de l'une de ces associations ?</h2>

        <div id="content">

        </div>

        <a href="javascript:void(0);" onclick="window.location.href='{{ path('association_new') }}'+this.dataset.name" class="btn btn-primary mt-3" id="confirm" data-name="">
            <i class="fa fa-save"></i>&nbsp;{{ 'association.pre_new.confirm'|trans }}
        </a>
    </div>

    <hr>

    <a href="{{ path('homepage') }}" class="btn btn-secondary">
        <i class="fa fa-arrow-left"></i>&nbsp;{{ 'association.add.cancel'|trans }}
    </a>
{% endblock %}